finalapp/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "users#discover"
  get 'newest', to: "home#newest"
  # get '/discover', to: "home#discover"
  get '/login', to: "home#login"
  resources :users, except: [:index, :destroy] do
    member do
      get 'feed', to: "users#feed"
      get 'discover', to: "users#discover"
    end
    resources :photos, shallow: true, except: :show
    resources :albums, shallow: true
  end
  namespace :admin do
    resources :albums, except: [:new, :create, :show]
    resources :photos, except: [:new, :create, :show]
    resources :users, except: [:new, :create, :show]
  end
end

finalapp/app/models/album.rb
class Album < ApplicationRecord
  validates :title, presence: true, length: {minimum: 10, message: "Album title should has more than 10 letters"}
  belongs_to :user, optional: true, counter_cache: :album_count
  has_and_belongs_to_many :photos
  has_many :likes, as: :content

  scope :sharing_mode, ->(public) {
    where(public: public)
  }

  before_save :ensure_description_has_a_value, :likes_count_not_nil
  private
  def ensure_description_has_a_value
    unless description.present?
      self.description = "This is album of user has id " + self.user_id.to_s
    end
  end
  def likes_count_not_nil
    if self.likes_count.nil?
      self.likes_count = 0
    end
  end
end

finalapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

finalapp/app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: "follower_id", class_name: "User"
  belongs_to :followee, foreign_key: "followee_id", class_name: "User"
end

finalapp/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :content, polymorphic: true, counter_cache: true
  belongs_to :user
end

finalapp/app/models/photo.rb
class Photo < ApplicationRecord
  validates :title, presence: true
  belongs_to :user, optional: true, counter_cache: :photo_count
  has_and_belongs_to_many :albums
  has_many :likes, as: :content

  mount_uploader :image, PhotoUploader

  before_save :likes_count_not_nil
  private
  def likes_count_not_nil
    if self.likes_count.nil?
      self.likes_count = 0
    end
  end
end

finalapp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :recoverable, and :omniauthable, :rememberable,
  devise :database_authenticatable, :registerable,
         :validatable, :confirmable, :recoverable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :photos, dependent: :destroy
  has_many :albums, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :follower_relationships, class_name: "Follow", foreign_key: :followee_id
  has_many :followers, through: :follower_relationships, source: :follower, dependent: :destroy  #@user.followers is list of users that follow this user

  has_many :followee_relationships, class_name: "Follow", foreign_key: :follower_id
  has_many :followees, through: :followee_relationships, source: :followee, dependent: :destroy  #@user.followees is list of users that this user follow


  validates :firstname, uniqueness: {scope: :lastname}
  validates_each :firstname, :lastname do |record, attr, value|
    record.errors.add(attr, "must start with upper case") if value =~ /\A[[:lower:]]/
  end
  with_options if: :admin? do |admin|
    admin.validates :password, length: {minimum: 10}
  end

  scope :admin, -> {where(admin: true)}

  # send sign up mail
  after_create :send_welcome_mail

  def name
    name = String.new("")
    if self.firstname.present?
      name = name + self.firstname + ' '
    end
    if self.lastname.present?
      name = name + self.lastname
    end
    return name
  end

  def avatar_name
    name = String.new("")
    if self.firstname.present?
      name += self.firstname[0]
    end
    if self.lastname.present?
      name += self.lastname[0]
    end
    return name
  end

  private
  def send_welcome_mail
    puts "after_save User"
    # UserMailer.with(user: self).welcome_mail.deliver_now
    SignUpMailerJob.perform_later self
  end
  # before_create :set_default_value_for_last_login
  # def set_default_value_for_last_login
  #   self.last_login = self.created_or_update
  # end


end

finalapp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def edit
    # render "edit"
    @album = Album.find(params[:id])
  end
  def update
    value = albums_title
    @album = Album.find(params[:id])
    @album.title = value
    if @album.update(title: value)
      flash[:title_change_error] = nil
      render "show"
    else
      flash[:title_change_error] = @album.errors.messages[:title][0]
      # render :edit
      redirect_to action: :edit
    end
  end
  def show
    @album = Album.find(params[:id])
    render "show"
  end

  private
  def albums_title
    params.require(:album).permit(:title)[:title]
  end
end

finalapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname])
  end
end

finalapp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to action: :newest
  end
  def newest
    @albums = Album.order(created_at: :desc).limit(4).select(:id, :title)
    render "newest"
  end

  def login

  end
  
end

finalapp/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # uploader = PhotoUploader.new
  def new
    @photo = Photo.new
    @user = User.find(get_user_id)
  end
  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = get_user_id
    if @photo.save
      redirect_to user_path(get_user_id)
    else
      @user = User.find(get_user_id)
      render "new"
    end
  end
  def edit
    @photo = Photo.find(get_photo_id)
    @user = User.find(@photo.user_id)
  end
  def update
    @photo = Photo.find(get_photo_id)
    @photo.update_attributes(photo_params)
  end
  def destroy
    Photo.destroy(get_photo_id)
  end

  private
  def get_user_id
    params.require(:user_id)
  end
  def photo_params
    params.require(:photo).permit(:title, :description, :sharing, :image)
  end
  def get_photo_id
    params.require(:id)
  end
end

finalapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])
    puts "User create action"

    if @user.save
      UserMailer.welcome_mail(@user).deliver_now
    end
  end
  def show

  end
  def feed

  end
  def discover
    @content_type = get_content
    @user = User.find(get_user_id)
    if @content_type == "photo"
      @content = Photo.includes(:user).order(updated_at: :desc)
    else
      @content = Album.includes(:user, :photos).order(updated_at: :desc)
    end
  end

  private
  def get_content
    if params[:content].present?
      params.require(:content)
    else
      "photo"
    end
  end
  def get_user_id
    if params[:id].present?
      params.require(:id)
    else
      current_user.id
    end
  end
end

finalapp/app/helpers/albums_helper.rb
module AlbumsHelper
end

finalapp/app/helpers/application_helper.rb
module ApplicationHelper
end

finalapp/app/helpers/home_helper.rb
module HomeHelper
end

finalapp/app/helpers/photos_helper.rb
module PhotosHelper
end

finalapp/app/helpers/users_helper.rb
module UsersHelper
end

finalapp/app/views/albums/edit.html.erb
<%= form_for @album, id: "form" do |f| %>
  <%= f.text_field(:title, value: "")%>
  <%= submit_tag("Edit") %>
<% end %>
<br>
<% if flash[:title_change_error] %>
  <%= flash[:title_change_error] %>
<% end %>
<%= javascript_pack_tag 'validation.js' %>

finalapp/app/views/albums/error.html.erb
<% if flash[:title_change_error] %>
  Title should be more than 10 letters
<% end %>

finalapp/app/views/albums/show.html.erb
<h1>Album <%=@album.id%>: </h1>
{
  Title: <%= @album.title %> <br>
  User_id: <%= @album.user_id %> <br>
  Created_at: <%= @album.created_at %> <br>
  Updated_at: <%= @album.updated_at %>
}

finalapp/app/views/home/discover.html.erb
<div class="container-fluid font">
  <div class="row bg justify-content-between home-bar" name="home-bar">
    <div class="row col-sm-6 col-8 align-items-center h-100 m-0 pr-0">
      <div class="col-4 pr-0 ml-3">
        <a class="navbar-brand float-right text-white" href="<%= discover_path %>" ><%= t ('.title') %></a>
      </div>
      <div class="col py-1 h-100 pr-0">
        <input class="col h-100 rounded border-0" type="text" name="search-bar" placeholder="Search Photo / Album"/>
      </div>
    </div>
    <nav class="navbar navbar-expand-sm row col-sm-6 col-4 m-0 p-0 justify-content-end">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#user-bar" aria-controls="user-bar" aria-expanded="false" aria-label="Toggle navigation">
        <a class="nav-toggle-icon btn rounded-circle bg-white text-color border-0 px-2">DP</a>
      </button>
      <div class="collapse navbar-collapse" id="user-bar" style="z-index: 100">
        <div class="navbar-nav col-12 justify-content-end align-items-center bg">
          <div class="col-3 row navbar-nav">
            <a href="<%= user_path(1)%>" class="nav-item nav-link btn rounded-circle bg-white text-color border-0 px-2">DP</a>
            <a href="<%= user_path(1)%>" class="nav-item nav-link btn text-white border-0">Duc Phu</a>
          </div>
          <div class="col-3 navbar-nav">
            <a class="nav-item nav-link btn text-white border-0" href="<%= login_path %>"><%= t ('logout') %></a>
          </div>
        </div>
      </div>
    </nav>
  </div>
  <div class="row bg-grey">
    <div class="col pt-4 align-items-center">
      <div class="row col ml-2">
        <a class="btn text-secondary" href="<%= feed_user_path(1)%>"><%=t ('feed') %></a>
      </div>
      <div class="row col ml-2">
        <a class="btn text-color" href="<%=discover_path%>" ><%= t('discover')%></a>
      </div>
    </div>
    <div class="col-sm-9 col-12 p-3">
      <div class="col bg-white">
        <div class="row justify-content-center">
          <div class="row m-3 btn-group">
            <!-- <button class="btn rounded-left border chosen" id="btn-photo" type="submit" ><%= t ('.photo') %></button> -->
            <%= button_to t('.photo'), {action: "discover", content: "photo"}, {class: "btn rounded-left border chosen", method: :get}%>
            <%= button_to t('.album'), {action: "discover", content: "album"}, {class: "btn rounded-left border bg-white", method: :get}%>
            <!-- <button class="btn rounded-right border bg-white" id="btn-album" type="submit"><%= t ('.album') %></button> -->
          </div>
        </div>
        <div class="row m-4 justify-content-between font-size">
          <% @content.each do |content|%>
            <%= render partial: "block", locals: {content: content}%>
          <% end %>
        </div>
        <div class="row bg-white mt-5 justify-content-center " style="height:50px">
          <div class="spinner-border text-secondary" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </div>
      </div>
    </div>
    <div class="col">
    </div>
  </div>
</div>
<!-- MODAL for PHOTO-->
<div id="modal-photo" class="modal" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content ">
      <div class="modal-header border-0">
        <p class="modal-title font-weight-bold" id="modal-photo-title"></p>
        <button type="button" class="photo-modal-close close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body my-n1 py-0">
        <img src="" class="img" id="modal-photo-body" style="width:100%"/>
        <p id="modal-photo-description" style="font-size:10px" class="pt-2"></p>
      </div>
    </div>
  </div>
</div>
  <!-- MODAL for ALBUM -->
  <div id="modal-album" class="modal" tabindex="-1" role="dialog"">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header border-0">
          <p class="modal-title font-weight-bold" id="modal-album-title"></p>
          <button type="button" class="album-modal-close close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body my-n1 py-0">
          <div id="carousel-modal" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="https://scontent.fsgn2-1.fna.fbcdn.net/v/t1.0-9/116212777_2941769292612649_3417797964556573653_o.png?_nc_cat=107&_nc_sid=09cbfe&_nc_ohc=reSenZfdMa0AX_P62Vw&_nc_ht=scontent.fsgn2-1.fna&oh=b036e28f8182b447d68134f50e3e2fdd&oe=5F746402" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="https://scontent.fsgn2-5.fna.fbcdn.net/v/t1.0-9/73533037_2872716039517975_2752281886001856581_o.jpg?_nc_cat=102&_nc_sid=0debeb&_nc_ohc=HltND1mRfboAX-sU2S8&_nc_ht=scontent.fsgn2-5.fna&oh=eeac0fa715bbcf1c379c6587c1a59446&oe=5F72E845" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="https://scontent.fsgn2-6.fna.fbcdn.net/v/t1.0-9/104590860_2837405519715694_3069445686140223906_o.png?_nc_cat=100&_nc_sid=174925&_nc_ohc=lRcMvR3vHkAAX_GMKDE&_nc_ht=scontent.fsgn2-6.fna&oh=adddbeb0296fc862f1ee47fee539c3c0&oe=5F7298E2" class="d-block w-100" alt="...">
              </div>
            </div>
            <a class="carousel-control-prev" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <p id="modal-album-description" style="font-size:10px" class="pt-2"></p>
        </div>
      </div>
  </div>
</div>

finalapp/app/views/home/newest.html.erb
<h1>4 lastest albums</h1>

<div class="row">
  <div class="col-12 col-sm-6">
    <%= @albums[0].title%><br>
    <%= @albums[1].title%>
  </div>
  <div class="col-12 col-sm-6">
    <%= @albums[2].title%><br>
    <%= @albums[3].title%>
  </div>
</div>

finalapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Fotobook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'script', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice%></p>
    <p class="alert"><%= alert%></p>
  </body>
</html>

finalapp/app/views/photos/edit.html.erb
<div class="container-fluid">
  <div class="row bg justify-content-between home-bar" name="home-bar">
    <div class="row col-sm-6 col-8 align-items-center h-100 m-0 pr-0">
      <div class="col-4 pr-0 ml-3">
        <a class="navbar-brand float-right text-white" href="<%= discover_user_path(content: "photo", id: @user.id) %>" ><%= I18n.t('brand') %></a>
      </div>
      <div class="col py-1 h-100 pr-0">
        <input class="col h-100 rounded border-0" type="text" name="search-bar" placeholder="Search Photo / Album"/>
      </div>
    </div>
    <nav class="navbar navbar-expand-sm row col-sm-6 col-4 m-0 p-0 justify-content-end">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#user-bar" aria-controls="user-bar" aria-expanded="false" aria-label="Toggle navigation">
        <a class="nav-toggle-icon btn rounded-circle bg-white text-color border-0 px-2"><%= @user.avatar_name%></a>
      </button>
      <div class="collapse navbar-collapse" id="user-bar" style="z-index: 100">
        <div class="navbar-nav col-12 justify-content-end align-items-center bg">
          <div class="col-auto row navbar-nav">
            <a href="<%= user_path(id: @user.id)%>" class="nav-item nav-link btn rounded-circle bg-white text-color border-0 px-2"><%= @user.avatar_name%></a>
            <a href="<%= user_path(id: @user.id)%>" class="nav-item nav-link btn text-white border-0"><%= @user.name%></a>
          </div>
          <div class="col-3 navbar-nav">
            <a class="nav-item nav-link btn text-white border-0" href="<%= login_path %>"><%= t ('logout') %></a>
          </div>
        </div>
      </div>
    </nav>
  </div>
  <div class="row bg-grey">
    <div class="col pt-4 align-items-center">
      <div class="col pt-4 align-items-center">
        <div class="row col ml-2">
          <%= link_to I18n.t('feed'), feed_user_path( @user.id ), {class: "btn text-secondary"}%>
        </div>
        <div class="row col ml-2">
          <%= link_to I18n.t('discover'), discover_user_path(content: "photo", id: @user.id), {class: "btn text-secondary"}%>
        </div>
      </div>
    </div>
    <div class="col-sm-9 col-12 p-3">
      <div class="col bg-white pb-3 mb-5">
        <div class="font-weight-bold border-bottom pt-4 pb-3 justify-content-between row mx-1" style="font-size:20px;">
          <div class="col">
            <%= t ('.header')%>
          </div>
          <div class="col-auto ">
            <%= link_to t('.back'), user_path(@user.id), {class: "btn chosen"}%>
          </div>
        </div>
        <%= form_for @photo do |f| %>
          <div class="row">
            <div class="col-12 col-sm px-4">
              <div class="form-group-vertical mt-4">
                <%= f.label :title, t('.title')%><br>
                <%= f.text_field :title, {placeholder: "Photo Title", class: "form-control col-11"}%>
              </div>
              <div class="form-group-vertical my-4">
                <%= f.label :sharing, t('.public_mode')%><br>
                <%= select_tag(:sharing,
                  options_for_select([
                  [t('.public'), "public"],
                  [t('.private'), "private"]
                  ], "public"),
                  {class: "col-5 custom-select"})%>
              </div>
            </div>
            <div class="col-12 col-sm px-4">
              <div class="form-group-vertical mt-4">
                <%= f.label :description, t('.description')%><br>
                <%= f.text_area :description, {placeholder: "Photo Description", class: "form-control", rows: "5", cols: "80"}%>
              </div>
            </div>
          </div>
          <div class="row mx-2 my-3">
            <div class="form-group-vertical bg-grey rounded add-photo" style="height:205px; width:205px">
              <%= image_tag @photo.image.thumb.url%>
            </div>
          </div>
          <div class="row mx-2 my-5 justify-content-between" style="width:200px;">
            <%= submit_tag t('.save'), {class: "btn add px-3"}%>
            <%= link_to t('.delete'), photo_path(params.require(:id)), {class: "btn delete px-3", method: :delete}%>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col">
    </div>
  </div>
</div>

finalapp/app/views/photos/new.html.erb
<div class="container-fluid font">
  <div class="row bg justify-content-between home-bar" name="home-bar">
    <div class="row col-sm-6 col-8 align-items-center h-100 m-0 pr-0">
      <div class="col-4 pr-0 ml-3">
        <a class="navbar-brand float-right text-white" href="<%= discover_user_path(content: "photo", id: params.require(:user_id)) %>" ><%= I18n.t('brand') %></a>
      </div>
      <div class="col py-1 h-100 pr-0">
        <input class="col h-100 rounded border-0" type="text" name="search-bar" placeholder="Search Photo / Album"/>
      </div>
    </div>
    <nav class="navbar navbar-expand-sm row col-sm-6 col-4 m-0 p-0 justify-content-end">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#user-bar" aria-controls="user-bar" aria-expanded="false" aria-label="Toggle navigation">
        <a class="nav-toggle-icon btn rounded-circle bg-white text-color border-0 px-2"><%= @user.avatar_name%></a>
      </button>
      <div class="collapse navbar-collapse" id="user-bar" style="z-index: 100">
        <div class="navbar-nav col-12 justify-content-end align-items-center bg">
          <div class="col-auto row navbar-nav">
            <a href="<%= user_path(params.require(:user_id))%>" class="nav-item nav-link btn rounded-circle bg-white text-color border-0 px-2"><%= @user.avatar_name%></a>
            <a href="<%= user_path(params.require(:user_id))%>" class="nav-item nav-link btn text-white border-0"><%= @user.name%></a>
          </div>
          <div class="col-3 navbar-nav">
            <a class="nav-item nav-link btn text-white border-0" href="<%= login_path %>"><%= t ('logout') %></a>
          </div>
        </div>
      </div>
    </nav>
  </div>
  <div class="row bg-grey">
    <div class="col pt-4 align-items-center">
      <div class="col pt-4 align-items-center">
        <div class="row col ml-2">
          <%= link_to I18n.t('feed'), feed_user_path( params.require(:user_id) ), {class: "btn text-secondary"}%>
        </div>
        <div class="row col ml-2">
          <%= link_to I18n.t('discover'), discover_user_path(content: "photo", id: params.require(:user_id)), {class: "btn text-secondary"}%>
        </div>
      </div>
    </div>
    <div class="col-sm-9 col-12 p-3">
      <div class="col bg-white pb-3 mb-5">
        <div class="font-weight-bold border-bottom py-4" style="font-size:20px;"><%= t ('.header')%></div>
        <%= form_for @photo, url: user_photos_path(user_id: params.require(:user_id)) do |f| %>
          <div class="row">
            <div class="col-12 col-sm px-4">
              <div class="form-group-vertical mt-4">
                <%= f.label :title, t('.title')%><br>
                <%= f.text_field :title, {placeholder: "Photo Title", class: "form-control col-11"}%>
              </div>
              <div class="form-group-vertical my-4">
                <%= f.label :sharing, t('.public_mode')%><br>
                <%= select_tag(:sharing,
                  options_for_select([
                  [t('.public'), "public"],
                  [t('.private'), "private"]
                  ], "public"),
                  {class: "col-5 custom-select"})%>
              </div>
            </div>
            <div class="col-12 col-sm px-4">
              <div class="form-group-vertical mt-4">
                <%= f.label :description, t('.description')%><br>
                <%= f.text_area :description, {placeholder: "Photo Description", class: "form-control", rows: "5", cols: "80"}%>
              </div>
            </div>
          </div>
          <div class="row mx-2 my-3">
            <div class="form-group-vertical bg-grey rounded add-photo" style="height:200px; width:200px">
              <%= f.file_field :image, {style: "opacity:0; height: 200px; width: 200px"}%>
            </div>
          </div>
          <div class="row mx-2 my-5">
            <%= submit_tag t('.save'), {class: "btn add px-3"}%>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col">
    </div>
  </div>
</div>

finalapp/app/views/users/_block.html.erb
<div class="col-sm-6 col-12 row bg-grey py-2 rounded shadow pr-0 mb-2">
  <div class="col-sm-6 col-12 pl-n1" >
    <img src="https://scontent.fsgn2-1.fna.fbcdn.net/v/t1.0-9/116212777_2941769292612649_3417797964556573653_o.png?_nc_cat=107&_nc_sid=09cbfe&_nc_ohc=reSenZfdMa0AX_P62Vw&_nc_ht=scontent.fsgn2-1.fna&oh=b036e28f8182b447d68134f50e3e2fdd&oe=5F746402" alt="doggo" class="img-fluid img-thumbnail" style="width:100%" />
  </div>
  <div class="col-sm-6 col-12 row mr-0 pr-0">
    <div class="row align-items-center col-12 mr-0 pr-0 justify-content-between" name="info-part">
      <div class="col-auto row">
        <div class="row col-auto">
          <button class="rounded-circle chosen border-0"><%= content.user.avatar_name%></button>
          <a href="#" class="btn font-size pl-1 "><%= content.user.name%></a>
        </div>
      </div>
      <div class="col-auto p-0 m-0 float-right">
        <button class="btn followed btn-sm font-size-sm p-0 rounded-pill">following</button>
      </div>
    </div>
    <div class="row font-weight-bold col-12" name="title-post"><%= content.title %> </div>
    <div class="row col-12" name="description-post"><%= content.description %></div>
    <div class="row justify-content-between align-items-end col-12 mr-0 pr-0">
      <div class="col text-color font-size love">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="12" height="12" fill="rgb(60, 90, 154)"><path fill-rule="evenodd" d="M7.655 14.916L8 14.25l.345.666a.752.752 0 01-.69 0zm0 0L8 14.25l.345.666.002-.001.006-.003.018-.01a7.643 7.643 0 00.31-.17 22.08 22.08 0 003.433-2.414C13.956 10.731 16 8.35 16 5.5 16 2.836 13.914 1 11.75 1 10.203 1 8.847 1.802 8 3.02 7.153 1.802 5.797 1 4.25 1 2.086 1 0 2.836 0 5.5c0 2.85 2.045 5.231 3.885 6.818a22.075 22.075 0 003.744 2.584l.018.01.006.003h.002z"></path></svg><span>  <%= content.likes_count%></span>
      </div>
      <div class="col-auto text-secondary font-size-sm mr-0 pr-0 text-right"><%= l content.updated_at, format: :last_update%></div>
    </div>
  </div>
</div>